package com.dr.saloon.utils

object AppConstaints {

    // colors
    const val COLOR_WHITE = "#FFFFFF"
    const val COLOR_GRAY_LIGHT = "#CACACA"
    const val COLOR_ROYAL_BLUE = "#4169e1"
    const val COLOR_SECONDARY_1 = "#342019"
    const val COLOR_PRIMARY_1 = "#fdd102"
    const val COLOR_RED = "#FF0000"
    const val COLOR_GREEN = "#008000"

    // const Offline Value

    const val INTENT_TYPE = "intentType"
    const val INTENT_TYPE_NOTIFICATION = "intentTypeNotification"
    const val MAP_API_KEY = "AIzaSyCjg18yyl3kYpiNlewvvvP2w2awI9wpaOA"
    const val TAB_COLLECTION = "HomePageTabs"
    const val USER_NAME = "name"
    const val PHONE = "phone"
    const val EMAIL = "email"
    const val BALANCE = "Balance"
    const val REFER_VALUE = "referValue"
    const val REFER_POLICY = "referPolicy"
    const val APPLY_REFERRAL_INCOME = "applyReferralIncome"
    const val APPLIED_REFER_BALANCE = "appliedReferBalance"
    const val REFERRAL_BALANCE = "referralBalance"
    const val IS_NOTIFICATION_ON = "isNotificationOn"
    const val TOTAL_APPOINTMENTS = "totalAppointments"
    const val TOTAL_CANCELLATION_CHARGE = "totalCancellationCharge"
    const val APPOINTMENT_CANCELLATION_CHARGE = "appointmentCancellationCharge"
    const val APPOINTMENT_CANCELLATION_CHARGE_COMMISSION = "appointmentCancellationChargeCommission"
    const val PROFILE_URL = "profileUrl"
    const val MY_LATITUDE = "latitude"
    const val MY_LONGITUDE = "longitude"
    const val LATITUDE = "latitude"
    const val LONGITUDE = "longitude"
    const val POP_UP_AD = "popUpAd"
    const val GENDER = "gender"
    const val PLACE_NAME = "placeName"
    const val MALE = "Male"
    const val SALON_TYPE = "salonType"
    const val SALON_TIMING = "timing"
    const val SERVICE_TYPE = "serviceType"
    const val FEMALE = "Female"
    const val UNISEX = "Unisex"
    const val COUNTRY_CODE = "countryCode"
    const val AUTH_STATUS = "Auth"
    const val AUTH_STATUS_INFO = "authStateInfo"
    const val AUTH_STATUS_DONE = "authDone"
    const val APPOINTMENT_STATUS = "appointmentStatus"
    const val APPOINTMENT_STATUS_PENDING = "Pending"
    const val APPOINTMENT_STATUS_CHECKED = "Checked"
    const val APPOINTMENT_STATUS_CANCELLED = "Cancelled"
    const val APPOINTMENT_CANCELLATION_DATE = "cancellationDate"
    const val APPOINTMENT_STATUS_DONE = "Done"
    const val APPOINTMENT_CANCELLATION_REASON = "cancellationReason"
    const val APPOINTMENT_CHARGE = "appointmentCharge"
    const val ARTICLE_URL = "articlesUrl"
    const val PAYMENT_API = "PaymentAPI"
    const val IS_SALON_AVAILABLE = "isAvailable"
    const val SALON_REVIEW_STATUS = "reviewStatus"
    const val SALON_REVIEW_STATUS_APPROVED = "approved"
    const val SALON_REVIEW_STATUS_PENDING = "pending"
    const val SALON_REVIEW_STATUS_REJECTED = "rejected"
    const val DAILY_USE_LIMIT = "dailyUseLimit"
    const val DAILY_USES = "dailyUses"
    const val UPLINK_UID = "upline"
    const val UPLINK_LEVEL = "upline"
    const val VIDEO_URL = "videoUrl"
    const val VIDEO_Id = "videoId"
    const val CATEGORIES = "categories"
    const val AMOUNT = "amount"
    const val RAZORPAY_API_KEY = "key_id"
    const val RAZORPAY_SECRET_KEY = "key_secret"
    const val IS_DATA_INITIALIZED = "isDataInitialized"
    const val IS_TASK_EARNING_SETTLED = "isTaskEarningSettled"
    const val UTILS_DOCUMENT = "Utils"
    const val STYLE_FOR_WEB_VIEW = "<style>img{display: inline; height: auto; max-width: 100%;}</style>"
    const val DEFAULT_ENCODING = "UTF-8"
    const val WEB_VIEW_MEME_TYPE_FOR_HTML = "text/html"
    const val ABOUT_US = "About Us"
    const val CONTACT_US = "Contact Us"
    const val PRIVACY_POLICY = "Privacy Policy"
    const val TERMS_AND_CONDITIONS = "Terms And Conditions"
    const val SHIPPING_POLICY = "Shipping Policy"
    const val REFUND_POLICY = "Refund Policy"
    const val COLLECTION_SLIDER = "Slider"
    const val COLLECTION_SERVICES = "Services"
    const val COLLECTION_TOP_CITIES = "TopCities"
    const val COLLECTION_TOP_METRO = "TopMetro"
    const val COLLECTION_TOP_SEARCH_CITIES = "TopSearchCities"
    const val COLLECTION_LOGIN_SLIDER = "LoginSlider"
    const val COLLECTION_NOTIFICATIONS = "Notifications"
    const val CITY_NAME = "cityName"
    const val COLLECTION_SALON = "Salon"
    const val COLLECTION_REVIEWS = "Reviews"
    const val COLLECTION_REVIEW_REPLIES = "Replies"
    const val COLLECTION_GALLERY = "Gallery"
    const val COLLECTION_APPOINTMENTS = "Appointments"
    const val LIKE_COUNT = "likeCount"
    const val MESSAGE = "message"
    const val COLLECTION_LIKED_USERS = "LikedUsers"
    const val LOG_OUT = "Log out"
    const val LOG_OUT_ALERT = "Are you sure want log out?"
    const val YES = "Yes"
    const val NO = "No"

    // Const Server Values

    const val USER_COLLECTION = "User"
    const val COLLECTION_REFER_INCOME = "ReferralIncome"
    const val COLLECTION_TASK_INCOME = "DailyTaskIncome"
    const val COLLECTION_VIDEOS = "Videos"
    const val COLLECTION_QUIZ = "Quiz"
    const val COLLECTION_WISH_LIST = "Wishlist"
    const val USER_ID = "userId"
    const val ORDER_ID = "orderId"
    const val YOUTUBE_API = "ytAPI"
    const val MY_COMMISSIONS = "MyCommissions"
    const val COLLECTION_TRANSACTIONS = "Transactions"
    const val MY_TASK_EARNING = "MyTaskEarning"
    const val PAYMENT_METHOD = "paymentMethod"
    const val LEVEL_PURCHASE = "levelPurchase"
    const val PERCENTAGE = "percentage"
    const val REMARK = "remark"
    const val COLLECTION_DAILY_TASKS_HISTORY = "DailyTasksHistory"
    const val NOTES_COLLECTION = "Notes"
    const val PRODUCT_COLLECTION = "Products"
    const val DEFAULT_ORDER_FIELD = "timestamp"
    const val PREFERENCE_SCORE = "preferenceScore"
    const val CONTROL_COLLECTION = "Controls"
    const val FIELD_USER_CODE = "UserCode"
    const val FIELD_TASK_DAY = "day"
    const val FIELD_REFERRAL_CODE = "ReferralCode"
    const val FIELD_RATING = "rating"
    const val STARTING_PRICE = "startingPrice"
    const val APP_LOGO_URL = "https://cdn-icons-png.flaticon.com/512/685/685681.png"

    // Const Texts

    const val DATE_TIME = "dateTime"
    const val THE_TITLE = "title"
    const val PAYMENT_STATUS = "paymentStatus"
    const val SLIDER_TAG = "tag"
    const val PAYMENT_STATUS_SUCCESS = "Success"
    const val PAYMENT_STATUS_PENDING = "Pending"
    const val PAYMENT_STATUS_CANCELLED = "Cancelled"
    const val SERVICE_NAME = "serviceName"
    const val SERVICE_ID = "serviceId"
    const val DATA_TYPE = "dataType"
    const val CASHFREE_API_KEY = "cashFreeApi"
    const val CASHFREE_SECRET_KEY = "cashFreeSecretKey"
    const val COLLECTION_PAYMENT_ORDERS = "PaymentOrders"
    const val SERVICE_COST = "serviceCharge"
    const val TOTAL_AMOUNT = "totalAmount"
    const val TOTAL_AMOUNT_PAID = "totalAmountPaid"
    const val SERVICES = "services"
    const val DISTANCE = "distance"
    const val DESCRIPTION = "description"
    const val CONTENT = "content"
    const val PRICE = "price"
    const val MRP = "mrp"
    const val RESPONSE = "response"
    const val IMAGE_URL = "imageUrl"
    const val SALON_NAME = "salonName"
    const val SALON_ADDRESS = "address"
    const val SALON_ID = "salonId"
    const val THEME_COLOR = "themeColor"
    const val LABEL = "label"
    const val IS_EDIT_MODE = "isEditMode"
    const val DOCUMENT_ID = "documentId"
    const val TIMESTAMP_FIELD = "timestamp"
    const val APP_VERSION = "appVersion"
    const val IP_ADDRESS = "ipAddress"
    const val SEARCH_TIME = "searchTime"
    const val LAST_TIME_UPDATE = "lastTimeUpdate"
    const val DEFAULT_DATE_FORMAT = "dd/MMM/yyyy hh:mm a"
    const val NO_LABEL = "No label"
    const val ADD_LABEL = "Add Label"
    const val TAB_NAME = "tabName"
    const val DELETE = "Delete"
    const val CONFIRM_DELETE = "Confirm delete"
    const val CONFIRM = "Confirm"
    const val DECLINE = "Decline"
    const val DELETED_SUCCESSFULLY = "Deleted Successfully"
    const val CURRENT_LEVEL = "CurrentLevel"
    const val PENDING_UPGRADE = "PendingUpgrade"

    // Error Messages

    const val ERROR_INVALID_PHONE = "Invalid Phone No."
    const val ERROR_ENTER_PHONE = "Enter Phone No."
    const val ERROR_ENTER_VERIFICATION_CODE = "Enter Verification Code"
    const val ENTER_NAME_ERROR = "Please enter your name"
    const val ENTER_EMAIL_ERROR = "Please enter email address"
    const val ERROR_INVALID_EMAIL = "Enter a valid email address"
    const val ERROR_INVALID_REFER_CODE = "Invalid ReferralCode"
    const val SERVER_ERROR = "Server Error"
    const val SOMETHING_WENT_WRONG = "Something went wrong. Please try again later."
    const val ERROR_ENTER_TITLE = "Please enter title"
    const val ERROR_ENTER_CONTENT = "Please enter content"
    const val NO_RESULT_FOUND = "No Result Found"

    const val IMAGE_3 = "https://firebasestorage.googleapis.com/v0/b/alex-9ae5d.appspot.com/o/image1.jpeg?alt=media&token=012fa786-abed-42f4-b7c6-a1d37407d869"
    const val IMAGE_2 = "https://firebasestorage.googleapis.com/v0/b/alex-9ae5d.appspot.com/o/image3.jpeg?alt=media&token=68494314-0e1f-47a6-99ca-a88c577d9e10"
    const val IMAGE_1 = "https://firebasestorage.googleapis.com/v0/b/alex-9ae5d.appspot.com/o/image2.jpeg?alt=media&token=2510fd5e-4b23-419b-af0f-f0f8a2d9981e"

}